version: 2
jobs:
  build:
    branches:
    docker:
      - image: sajidanower23/github-migration
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            # Always cache everything
            - deps-
      - save_cache:
          name: Cache Dependencies
          key: deps-
          paths:
            - ~/.stack
      - run:
          name: Build & Test App
          working_directory: '~/github-migration'
          command: |
            stack setup
            stack build
            stack test
